version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 3002:3002
    depends_on:
      backend:
        condition: service_started
    environment:
      BACKEND_URL: "backend:3001"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 3001:3001
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: "database:27017"

  database:
    image: mongo:7.0.7-rc2-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init-database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: mongosh --port 27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s
