version: "3.8"

services:
  # SYSTEM UNDER TEST
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 30002:3002
    depends_on:
      backend:
        condition: service_started
    environment:
      PORT: 3002
      BACKEND_URL: "backend:3001"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 30001:3001
    depends_on:
      database:
        condition: service_healthy
      api-mock:
        condition: service_started
    environment:
      PORT: 3001
      DATABASE_URL: "database:27017"
      COINCAP_URL: "http://api-mock:3003/coincap"

  database:
    image: mongo:7.0.7-rc2-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./init-database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    healthcheck:
      test: mongosh --port 27017 --quiet
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 5s

  # TEST ENVIRONMENT
  tests:
    build:
      context: .
      dockerfile: Dockerfile.tests
    environment:
      CYPRESS_BASE_URL: "http://frontend:3002"

  api-mock:
    build:
      context: .
      dockerfile: Dockerfile.api-mock
    ports:
      - 3003
    environment:
      PORT: 3003
