FROM node:21-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /home/node/app

COPY ./api-mock/package*.json ./

USER node
RUN yarn install
COPY --chown=node:node ./api-mock .
CMD [ "node", "app.js" ]