on: [push]
jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Debug
        run: ls
      - name: Start Docker Compose Environment
        run: docker compose up -d
      - name: Run Tests
        run: docker compose exec -T tests yarn cypress run --headless
      - name: Stop Docker Compose Environment
        run: docker compose stop
